name: mcumgr
description: Dart client for the mcumgr embedded device management protocol.
version: 0.1.0
repository: https://github.com/metratec/mcumgr-dart

environment:
  sdk: ^3.0.0

dependencies:
  cbor: ^6.2.0

dev_dependencies:
  test: ^1.24.0
